### PR TITLE
(fix) : close overlays to return to stock item operations

### PR DESCRIPTION
**Pull request by jabahum**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR closes overlays, fixes  stock item quantities and  batch information from disappearing

### CODE REVIEW

**Comment by hadijahkyampeire** [comment]
@jabahum is this ready for review?

**Comment by jabahum** [comment]
> @jabahum is this ready for review?

yes its ready you can run through and provide feedback

**Comment by makombe** [comment]
@jabahum Please resolve conflicts and you can also share screenshot/video for the change. Thanks

**Comment by ojwanganto** [comment]
@jabahum please resolve the conflicts so that this can be reviewed.

**Comment by hadijahkyampeire** [comment]
@jabahum I am going to go ahead and close this, we shall have a new PR once we discuss fully how we want to handle navigation.

**Pull request closed without merging**
