### PR TITLE
(feat)- O3-3966: At stock requisition, user should be able to see the number of the stock item and its availability

### PR DESCRIPTION
**Pull request by TrevorAntony**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR allows the user to see if a stock item is 'Out of Stock' or 'Available' as well as the total quantity of the stock item available across all its batches.

## Screenshots
Screenshot 2024-11-13 at 13 43 40

## Related Issue
https://openmrs.atlassian.net/browse/O3-3966

### CODE REVIEW

**Comment by TrevorAntony** [comment]
@jabahum Should this be limited to only the stock requisition operation? Left it open for now

**Comment by TrevorAntony** [comment]
Should this be limited to only the 'requisition' operation. Left it open for now

**Comment by jabahum** [comment]
> Should this be limited to only the 'requisition' operation. Left it open for now

cc @slubwama

**Comment by jabahum** [comment]
> Should this be limited to only the 'requisition' operation. Left it open for now

For now i think so.

**Comment by jabahum** [comment]
@TrevorAntony maybe a quick question is this implementation dependant on the location. or we are focusing on looking for a available stock in the main store.

**Comment by TrevorAntony** [comment]
> @TrevorAntony maybe a quick question is this implementation dependant on the location. or we are focusing on looking for a available stock in the main store.

we are focusing on looking for available stock in the main store

**Review by jabahum — APPROVED** [review]

**Pull request merged**
