### PR TITLE
Modification of search function to enable filter in search

### PR DESCRIPTION
**Pull request by gabriel090**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
Modification of search function to enable filter in search

Modification of search function to enable filter search
## Screenshots
userSearch

userSearch

### CODE REVIEW

**Review by jabahum — COMMENTED** [review]
Thanks @gabriel090  i have a question though what happens to the choose role select when you select a user. Can you share a gif of that as well

**Comment by gabriel090** [comment]
> Thanks @gabriel090 i have a question though what happens to the choose role select when you select a user. Can you share a gif of that as well

Hi, Jaba. Do you mean the outcome submission, once the user role is selected?.

**Review by makombe — APPROVED** [review]

**Review by makombe — CHANGES_REQUESTED** [review]
@gabriel090 It seems this change affect the population of user roles. Please test and ensure everything is in sync and you are able to add a new user role perfectly as it is currently. Thanks

**Comment by gabriel090** [comment]
> > Thanks @gabriel090 i have a question though what happens to the choose role select when you select a user. Can you share a gif of that as well
> 
> Hi, Jaba. Do you mean the outcome submission, once the user role is selected?.

OK. I have checked and tested. Its working
billableRole

**Comment by gabriel090** [comment]
> @gabriel090 It seems this change affect the population of user roles. Please test and ensure everything is in sync and you are able to add a new user role perfectly as it is currently. Thanks

Thanks. I have fixed the issue

**Review by jabahum — APPROVED** [review]
Thanks @gabriel090

**Comment by donaldkibet** [comment]
Thanks @jabahum @makombe @gabriel090 merging this

**Review by makombe — APPROVED** [review]

**Pull request merged**
