### PR TITLE
Feat/o3 3671 Cancel button for Packaging Units

### PR DESCRIPTION
**Pull request by patryllus**
[Screencast from 29-07-2024 05:56:06 ALASIRI.webm](https://github.com/user-attachments/assets/aa792fd5-d17b-4a75-bc1a-a16e2f1c507c)

### CODE REVIEW

**Review by jabahum — COMMENTED** [review]
@patryllus Thanks . Though  lets route stock Item and not the items list

**Comment by ojwanganto** [comment]
> @patryllus Thanks . Though lets route to stock Item and not the items list

+1

**Comment by patryllus** [comment]
@jabahum @ojwanganto Updated PR reviews:  Reroute cancel button on packaging unit  to stock item and not item list

**Comment by patryllus** [comment]
[Screencast from 30-07-2024 10:59:33 ASUBUHI.webm](https://github.com/user-attachments/assets/d2b68e66-7d29-4476-a213-73728f745891)

**Review by jabahum — APPROVED** [review]
LGTM @patryllus thanks

**Pull request merged**
