### PR TITLE
StockManagement(Add pack size at quantities view)

### PR DESCRIPTION
**Pull request by charity553**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

[Screencast from 17-08-2024  2:29:14 WB.webm](https://github.com/user-attachments/assets/0b1a0d5b-99c9-42ab-9d9b-6e733bcbb994)

### CODE REVIEW

**Comment by ojwanganto** [comment]
Is the pack size not already part of the packaging unit?

**Comment by charity553** [comment]
@ojwanganto yes it is available in the Packaging units but they were requesting it to be added on the the Quantitties too

**Comment by makombe** [comment]
@charity553 I think we are just repeating ourselves and making the UI busy we just need to advice our users that what they are asking for is already displayed under packaging unit. Thanks

**Comment by charity553** [comment]
@makombe Noted

**Comment by ojwanganto** [comment]
Thanks, @charity553. I agree with @makombe since in the packaging unit I can see Table of 1 of which 1 is actually the pack size.

**Review by jabahum — APPROVED** [review]

**Comment by jabahum** [comment]
@makombe do we still need this PR in ?? or we maintain what we have because i also see replications of features here

**Comment by hadijahkyampeire** [comment]
@charity553 does this have a ticket? Is it a fix or chore, the PR title should follow the conventions

**Comment by hadijahkyampeire** [comment]
@jabahum I thought you already worked on this?

**Comment by makombe** [comment]
@hadijahkyampeire This lets close it. Thanks @charity553  for working on this.

**Pull request closed without merging**
