### PR TITLE
(fix):O3-3227 Fix error when issuing stock

### PR DESCRIPTION
**Pull request by makombe**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

https://www.loom.com/share/a615685f805a45268fc69c0a9b064b7f

### CODE REVIEW

**Comment by makombe** [comment]
> @makombe thanks can u share a video or gif. ??

@jabahum I have shared a loom link under screenshots.

**Comment by jabahum** [comment]
@makombe can we add auto refresh after stock operation instead of switching between pages

**Comment by makombe** [comment]
> @makombe can we add auto refresh after stock operation instead of switching between pages

@jabahum that is already handled here [here](https://github.com/openmrs/openmrs-esm-stock-management/blob/6276df7d2b575956b5e8dce18e40d097903b072a/src/stock-operations/stock-operation.utils.tsx#L36) I think I was trying to move faster for the purposes of recording

**Comment by jabahum** [comment]
> > @makombe can we add auto refresh after stock operation instead of switching between pages
> 
> @jabahum that is already handled [here](https://github.com/openmrs/openmrs-esm-stock-management/blob/6276df7d2b575956b5e8dce18e40d097903b072a/src/stock-operations/stock-operation.utils.tsx#L36) I think I was trying to move faster for the purposes of recording

Thanks @makombe maybe a follow up PR to add something like below on the requistion operation
image

**Review by jabahum — APPROVED** [review]
Thanks @makombe

**Pull request merged**
