### PR TITLE
(feat) Add filters to stock operations table

### PR DESCRIPTION
**Pull request by kajambiya**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR adds filters to the stock operations table. 

## Screenshots

https://github.com/openmrs/openmrs-esm-stock-management/assets/12844964/56eed0d7-ee64-4ef1-aabe-44fd68ad80f6

### CODE REVIEW

**Comment by makombe** [comment]
Thanks @kajambiya LGTM!. One observation from the video, can we make the item list name from the drop down to be visible? Seems when you open the dropdown the text are truncated. The dropdown should be responsive, they should be visible at a glance without the user struggling to read. Thanks

**Comment by kajambiya** [comment]
> Thanks @kajambiya LGTM!. One observation from the video, can we make the item list name from the drop down to be visible? Seems when you open the dropdown the text are truncated. The dropdown should be responsive, they should be visible at a glance without the user struggling to read. Thanks

Thanks @makombe, yah as mentioned in the summary, I'm still fixing some stylings. Just needed folks to review the logic so that after fixing the styles, the PR can move from draft to actual.

**Review by jabahum — COMMENTED** [review]
Thanks @kajambiya LGTM so same here lets have the styling in there

**Comment by jabahum** [comment]
Thanks @kajambiya. The pagination seems not to be working as expected. I have shared a video below

https://github.com/openmrs/openmrs-esm-stock-management/assets/24471994/64e6703f-0fe0-4a4d-b1cd-e91526d268f1

**Comment by kajambiya** [comment]
> Thanks @kajambiya. The pagination seems not to be working as expected. I have shared a video below
> 
>  Screen.Recording.2024-02-21.at.08.48.40.mov

Nice catch man. Let me fix it ASAP

**Comment by kajambiya** [comment]
> Thanks @kajambiya. The pagination seems not to be working as expected. I have shared a video below
> 
>  Screen.Recording.2024-02-21.at.08.48.40.mov

@jabahum the pagination issue has been fixed. Please review and revert.

**Comment by jabahum** [comment]
@kajambiya Thanks LGTM

**Review by jabahum — APPROVED** [review]

**Pull request merged**
