### PR TITLE
(fix)  : Unable to edit operations due to userrolescopes being coupled with user privileges 

### PR DESCRIPTION
**Pull request by jabahum**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by hadijahkyampeire** [comment]
@jabahum is this ready for review, sorry I have also created a ticket with the same solution, we should merge one of these to unblock people.

**Comment by jabahum** [comment]
> @jabahum is this ready for review, sorry I have also created a ticket with the same solution, we should merge one of these to unblock people.

noted @hadijahkyampeire was just finalising with this but we can laise and see what we both then we merge in one

**Comment by ojwanganto** [comment]
@hadijahkyampeire - which is the duplicate PR?

**Comment by hadijahkyampeire** [comment]
@jabahum let's close this since it is already fixed

**Pull request closed without merging**
