### PR TITLE
(O3-3310) : On deleting a packaging unit, an error is thrown rather than a popup dialogue to add a reason for deleting the packaging unit

### PR DESCRIPTION
**Pull request by Daphne210**
https://github.com/openmrs/openmrs-esm-stock-management/assets/89844768/b84a3525-ada9-4e20-86d5-9af4f2ad74b4

### CODE REVIEW

**Comment by jabahum** [comment]
@Daphne210 thanks. What happens when the yes button on the dialog is clicked

**Comment by Daphne210** [comment]
> @Daphne210 thanks. What happens when the yes button on the dialog is clicked


https://github.com/openmrs/openmrs-esm-stock-management/assets/89844768/39602b5e-1dc4-49fb-8c17-628e274ebaf5


same error from 2.x as seen in the attached file

**Comment by jabahum** [comment]
> > @Daphne210 thanks. What happens when the yes button on the dialog is clicked
> 
>  20240524174042.mp4 
> same error from 2.x as seen in the attached file

@slubwama can kindly help fix this issue when deleting packing units and this is also happening deleting references items both on 2.x and 03

**Comment by makombe** [comment]
This is a  backend error. There is a stray bracket on the query making it to fail. I remember fixing this locally on our end. Let me make that PR @jabahum

**Comment by jabahum** [comment]
> This is a backend error. There is a stray bracket on the query making it to fail. I remember fixing this locally on our end. Let me make that PR @jabahum

Thanks @makombe

**Comment by jabahum** [comment]
> @jabahum This has be addressed through this PR [here](https://github.com/openmrs/openmrs-module-stockmanagement/pull/22)

Thanks @makombe

**Pull request closed without merging**
