### PR TITLE
O3-3695-Show received stock items list after a stock issue operations has been disp

### PR DESCRIPTION
**Pull request by TrevorAntony**
## Summary
Show received stock items list after a stock issue operations has been dispatched. It allows A user  to see alist of stock items he/she received  only after a completed ,dispatched stock issue

## Screenshots
Screenshot 2024-08-06 at 10 43 59
Screenshot 2024-08-06 at 10 44 07

## Related Issue
https://openmrs.atlassian.net/browse/O3-3695

### CODE REVIEW

**Review by jabahum — CHANGES_REQUESTED** [review]
This should be visible for only stock issue operation.

**Comment by TrevorAntony** [comment]
> This should be visible for only stock issue operation. You can have a quick ran through on 2.x just to see how the flow is

Made the requested changes so the list is only visible for Stock Issue

**Comment by jabahum** [comment]
> > This should be visible for only stock issue operation. You can have a quick ran through on 2.x just to see how the flow is
> 
> Made the requested changes so the list is only visible for Stock Issue

thanks. there's also last thing i think we need to consider, thats an operation can have permissions attribute.
```
let canReceiveItems =
          stockOperation?.permission?.canReceiveItems ?? false;
```
so lets be mindful of it  which means the operation for which received items can show can change depending on this operation.

**Review by jabahum — APPROVED** [review]
Thanks @TrevorAntony LGTM

**Pull request merged**
