### PR TITLE
(fix) O3-3800 : Error occurs while save or completing an operation

### PR DESCRIPTION
**Pull request by jabahum**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

https://github.com/user-attachments/assets/405d3abb-a368-4612-9bbd-10ecb48c5681

https://github.com/user-attachments/assets/247509bc-6055-47cb-b967-eea58d8eb609

## Related Issue

https://openmrs.atlassian.net/browse/O3-3800

### CODE REVIEW

**Comment by makombe** [comment]
@jabahum can you provide video where you can successfully complete an operation, thanks.

**Comment by jabahum** [comment]
noted

**Comment by makombe** [comment]
@jabahum I have tried testing this locally seems to be failing because of roles yes I have assigned the user scope roles accordingly. Can you check on that as well. Thanks

**Comment by jabahum** [comment]
> @jabahum I have tried testing this locally seems to be failing because of roles yet I have assigned the user scope roles accordingly. Can you check on that as well. Thanks

what error is this returning for you

**Comment by jabahum** [comment]
i have updated the PR to fix the issues on complete so it should be working fine now cc @makombe , @hadijahkyampeire

**Comment by makombe** [comment]
Thanks @jabahum  for the update. A quick one from the operation table in the video, I remember edit feature was moved to overflow menu to be in sync with most of community designs. Are we like undergoing some form of regression with stock?  cc @hadijahkyampeire @slubwama @TrevorAntony @donaldkibet @patryllus 

Screenshot from 2024-08-21 10-33-52

**Comment by jabahum** [comment]
> Thanks @jabahum for the update. A quick one from the operation table in the video, I remember edit feature was moved to overflow menu to be in sync with most of community designs. Are we like undergoing some form of regression with stock? cc @hadijahkyampeire @slubwama @TrevorAntony @donaldkibet @patryllus
> 
> Screenshot from 2024-08-21 10-33-52

Just aligning this with 3.x and also the actions on the operations were not consistent with those in the items tables.

**Review by makombe — APPROVED** [review]
Thanks @jabahum LGTM. For translations, we should only update in English and not other languages

**Comment by jabahum** [comment]
> Thanks @jabahum LGTM. For translations, we should only update in English and not other languages

Thanks this is noted

**Pull request merged**
