### PR TITLE
(Fix): O3-3780 Error displaying To and From location fields while editing

### PR DESCRIPTION
**Pull request by TrevorAntony**
## Summary
While editing a stock-item operation, the fields To and  FROM were erroneously displayed as LOCATION  and without default data that was previously input during the initial stock operation. This has been resolved

## Screenshots
Screenshot 2024-08-19 at 12 46 50
Screenshot 2024-08-19 at 12 46 59

## Related Issue
https://openmrs.atlassian.net/browse/O3-3780

### CODE REVIEW

**Comment by jabahum** [comment]
@TrevorAntony Can we validate this for other operations and see how its working . and also resolve conflicts

**Comment by TrevorAntony** [comment]
> @TrevorAntony Can we validate this for other operations and see how its working . and also resolve conflicts

Ok

**Comment by jabahum** [comment]
@TrevorAntony this looks good. Can we update this PR by resolving the conflicts so we move this in

**Review by jabahum — COMMENTED** [review]
Lets handle the conflicts

**Review by jabahum — COMMENTED** [review]
@TrevorAntony thanks there are few fixes we need to make  for example while editing a operation lets sat opening stock i still see a To yet its not supposed to be there refer to the second screenshot of 3.x
image
image

**Comment by jabahum** [comment]
@TrevorAntony also wen editing and status of the operation is completed we shouldnt be able to edit the fields again especially the dropdowns
o3
image
2.x
image

**Comment by TrevorAntony** [comment]
Kindly review. Was able to address the 'complete' status issue. Still working on the fields being rendered for different operations

**Comment by jabahum** [comment]
> Kindly review. Was able to address the 'complete' status issue. Still working on the fields being rendered for different operations

how far with this @TrevorAntony

**Comment by TrevorAntony** [comment]
> > Kindly review. Was able to address the 'complete' status issue. Still working on the fields being rendered for different operations
> 
> how far with this @TrevorAntony

Just done the final commit. All fields should be working as expected

**Review by jabahum — COMMENTED** [review]
Thanks @TrevorAntony looks good , just one more comment and fix. 
So while adding new operation ` From input` has locations which have been  assigned to do operations. But when editing the locations returns all locations 
Editing   Operation
Screenshot 2024-08-26 at 11 48 09
Adding new Operation
Screenshot 2024-08-26 at 11 49 06

while adding new stock take operation, reason  drop takes for ever to load.
Screenshot 2024-08-26 at 12 00 52

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @TrevorAntony LGTM

**Pull request merged**
