### PR TITLE
(Test): O3-3755: Add Tests for stock item bulk import

### PR DESCRIPTION
**Pull request by TrevorAntony**
## Summary
The tests should look out for if the files being imported is only a csv, is less than 2mbs as well as tests for the cancel button and upload stock items button, verify that the component renders with the initial state and UI elements are correctly displayed. 
File selection: Test the file selection functionality to ensure that a file can be selected and stored in the state.
Upload confirmation without file ensure that the upload function does nothing if no file is selected.
Mock the UploadStockItems function to simulate a successful upload and ensure the success snackbar is shown and the modal is closed.
Mock the UploadStockItems function to simulate a failed upload and ensure the error snackbar is shown, and translation of the file

## Related Issue
https://openmrs.atlassian.net/browse/O3-3755

### CODE REVIEW

**Comment by TrevorAntony** [comment]
@CynthiaKamau @ODORA0

**Comment by ODORA0** [comment]
@jabahum Could you have a look at this?
There's a check for if a file is less than or equal to 2mbs and am not certain if that is what we would need to do.

**Comment by jabahum** [comment]
I think the file can grow bigger because each facility might have there own list of drugs so I would rather we left it open or give it a max value of maybe 10mbz as the biggest we can have.

**Comment by TrevorAntony** [comment]
> I think the file can grow bigger because each facility might have there own list of drugs so I would rather we left it open or give it a max value of maybe 10mbz as the biggest we can have.

i will move forward with leaving it open

**Review by ODORA0 — APPROVED** [review]
LGTM

**Comment by ODORA0** [comment]
@jabahum Can you have a look and approve once all is good

**Review by jabahum — APPROVED** [review]
LGTM

**Pull request merged**
