### PR TITLE
Fix : Ensured the default Packaging Unit is selected

### PR DESCRIPTION
**Pull request by FelixKiprotich350**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
Ensured the default Dispensing packaging unit and default stock operations packaging unit is selected on saving after editing or adding 

## Screenshots
[stock-default-selection.webm](https://github.com/user-attachments/assets/094a2e70-42c6-4891-b155-182c48ec4c1e)

## Related Issue
https://openmrs.atlassian.net/browse/O3-3703

### CODE REVIEW

**Comment by FelixKiprotich350** [comment]
@donaldkibet check this

**Review by donaldkibet — APPROVED** [review]
LGTM Thanks @FelixKiprotich350

**Comment by ojwanganto** [comment]
Thanks, @FelixKiprotich350 and @donaldkibet

**Comment by FelixKiprotich350** [comment]
@ojwanganto also check on radiology

**Pull request merged**
