### PR TITLE
(O3-3335) : Enable search item with stock item pages

### PR DESCRIPTION
**Pull request by agesa3**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

https://github.com/openmrs/openmrs-esm-stock-management/assets/47299413/886e271b-4f5e-44a3-be85-ca1515ef5ae5

### CODE REVIEW

**Review by jabahum — COMMENTED** [review]
Thanks @agesa3 can you share a gif or vid

**Comment by agesa3** [comment]
> Thanks @agesa3 can you share a gif or vid

I did a video check on the readme I have for the PR.



> Thanks @agesa3 can you share a gif or vid

**Review by jabahum — COMMENTED** [review]
Thanks @agesa3 LGTM.

**Review by jabahum — APPROVED** [review]

**Comment by ojwanganto** [comment]
We can later discuss whether we should load all stock items or rather provide a search and only render the stock item of interest. Am concerned about the data that has to be pulled down when in real sense one may only be interested in a single stock item and its operations

**Comment by agesa3** [comment]
> We can later discuss whether we should load all stock items or rather provide a search and only render the stock item of interest. Am concerned about the data that has to be pulled down when in real sense one may only be interested in a single stock item and its operations

Currently, the table fetches only the first 10 stock items initially. As you paginate, it hits the server again to fetch the next 10 items. If I understand correctly, the suggestion is to replace this approach with a search input. Instead of rendering stock items by default, the table would only be populated with items searched for by the user.

**Pull request merged**
